### ISSUE TITLE
Avoid installing simplejson for python > 2.5

### ISSUE THREAD

**Issue by boivie** [uri-templates/uritemplate-py#28]
Installing uritemplate on a python-2.7 installation results in simplejson being installed as well, and bundled with your application (in your requirements.txt-file when you freeze your dependencies)

Json parsing is only needed for running tests, and only for python <= 2.5. It's completely okey to let those few people install it manually when required.

**Comment by mnot** [comment]
Taken care of in 35b632; just need to do a release.
